# cub6_8
PROJECT_NAME: "PSVMAPP_cub"
OUTPUT_DIR: "checkpoints"
LOG_FILE_NAME: "results.log"
MODEL_FILE_NAME: "best_model.pth"
MODEL:
  META_ARCHITECTURE: "Model"
  SEED: 114514
  SCALE: 30.0 #25.0
  BACKBONE:
    PRETRAINED: True
  ATTENTION:
    CHANNEL: 512
    # W2V_PATH: "../datasets/Attribute/w2v"
    W2V_PATH: "w2v"
  LOSS:
    LAMBDA1: 1.0 #1.0
    LAMBDA2: 0.5 
    LAMBDA3: 0.001 #0.001 
    LAMBDA4: 5.0 #5.0

DATASETS:
  NAME: "CUB"
  IMAGE_SIZE: 224  
  WAYS: 16 
  SHOTS: 3

DATALOADER:
  MODE: 'episode'
  N_BATCH: 300

SOLVER:
  MAX_EPOCH: 25 
  BASE_LR:  1e-3 
  WEIGHT_DECAY: 1e-4 
  MOMENTUM: 0.9
  GAMMA: 0.1
  STEPS: 5 
  DATA_AUG: "resize_random_crop"

TEST:
  IMS_PER_BATCH: 100
  DATA_AUG: "resize_crop"
  GAMMA: 2.0 #1.5
